services:
  dnsserver:
    build: dnsserver
    hostname: dnsserver
    ports:
      - 127.0.0.1:53:53
    networks:
      rededns:
          ipv4_address: 192.168.20.100
    volumes:
      - ./dnsserver/conf/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/conf/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./dnsserver/conf/db.20.168.192:/etc/bind/db.20.168.192
  eq1:
    build: debian
    hostname: darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    dns: 192.168.20.100
  dnsserver2:
    build: dnsserver2
    hostname: darthsidious
    depends_on:
      - dnsserver
    networks:
      rededns:
        ipv4_address: 192.168.20.11
    volumes:
      - ./dnsserver2/conf/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver2/conf/named.conf.local:/etc/bind/named.conf.local
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

